fill_sample <- function(session) {
  updateTextInput(session, 's_name', value = 'Matthew Webb')
  updateTextInput(session, 's_email', value = 'mwebb@channelswimmingassocation.com')
  updateSelectInput(session, 's_gender', selected = 'male')
  updateTextInput(session, 's_phone', value = '505-867-5309')
  updateTextAreaInput(session, 's_mailing', value = '121 Main St, Dover, England')
  updateTextInput(session, 'ec_name', value = 'Madeline Chaddock')
  updateTextInput(session, 'ec_rel', value = 'spouse')
  updateTextInput(session, 'ec_phone', value = '212-121-2121')
  updateTextInput(session, 'ec_email', value = 'mchaddock@gmail.com')
  updateTextAreaInput(session, 'experience', value = "Lots of experience")
  updateCheckboxInput(session, 'med1', value = 1)
  updateCheckboxInput(session, 'med2', value = 1)
  updateTextInput(session, 'initial1', value = 'mw')
  updateTextInput(session, 'initial2', value = 'mw')
  updateTextInput(session, 'initial3', value = 'mw')
  updateTextInput(session, 'initial4', value = 'mw')
  updateTextInput(session, 'initial5', value = 'mw')
  updateTextInput(session, 'initial6', value = 'mw')
  updateTextInput(session, 'initial7', value = 'mw')
  updateTextInput(session, 'initial8', value = 'mw')
  updateTextInput(session, 'initial9', value = 'mw')
  updateTextInput(session, 'initial10', value = 'mw')
  updateTextInput(session, 'initial11', value = 'mw')
  updateTextInput(session, 'waiver_sig', value = 'Matthew Webb')
  updateCheckboxInput(session, 'waiver_box', value = 1)
  updateSelectInput(session, 'team_name', selected = 'Deep Enders')
}